### ISSUE TITLE
Compute which elevator will take external request

### ISSUE THREAD

**Issue by dagerikhl** [BourgondAries/elevators#16]
1. Merge servicing filtered on external requests
2. Subtract all servicing from external requests
3. For each external requests:
    1. Find canditate (heading in the right direction or no servicing)
    2. Find score of all candidates (score according to current floor and direction)
    3. Filter negative or positive scores (according to direction of request)
    4. Filter by top score
    5. Sort top scorers by uuid
    6. Assign task to first top scorer

**Comment by kstrafe** [comment]
About done! b713ae8740771d5cbd38a17d0a2befc7b33d304c

Will need to test a fair bit though. Only used in the simulator atm.
