### ISSUE TITLE
Remove done requests and open door

### ISSUE THREAD

**Issue by dagerikhl** [BourgondAries/elevators#18]
1. If floor equals floor of first servicing request:
    1. Open door
    2. Remove servicing request
    3. If request was external:
        1. Add request to done requests
        2. Recur
    4. If request was internal:
        1. Remove request from internal requests
        2. Recur

**Comment by kstrafe** [comment]
Done! 3f12896d4a2b30fe3cfe184bb0bc9781aed33ff2
