### ISSUE TITLE
Parameterize the this: functions using units

### ISSUE THREAD

**Issue by kstrafe** [BourgondAries/elevators#23]
Utilities depends on global state (id) defined in data-structures.

GOOD: It's immutable.
BAD: It's global.

It'd be awesome to instead create a first-class unit taking an ID and giving us all these functions using the parameterized ID.

https://docs.racket-lang.org/guide/firstclassunits.html

**Comment by dagerikhl** [comment]
Note: Both `id` and `name` are global, and both are used in both `utilities.rkt` and `core.rkt`.

**Comment by dagerikhl** [comment]
1. Create new file to handle unit-initialization, eg. `initiator.rkt`.
2. Make `core` and `utilities` into units that take `id` (and `name` for `core`).
    * Let them use unit-parameters in stead of global variables.
3. Move id and name generation from `data-structures` to `initiator`.
4. Move all `this:` and `other:` from `data-structures` to `utilities`.
5. Connect `main` to `initiator` in stead of `core`.
6. Let reload send `'(complex id name)` in stead of just `complex` to avoid `core` and `utilities` losing information about `id` and `name` on reload.
    * Should test that this is necessary first.

**Comment by dagerikhl** [comment]
Done! 511ab23
