### ISSUE TITLE
Add special-case handling of top and bottom floors with command

### ISSUE THREAD

**Issue by dagerikhl** [BourgondAries/elevators#32]
### Situation

Serving command and up on bottom floor or command and down on top floor will cause the elevator not to take the call.

### Reproduce

* `command 0`
* `call up 0`
_or_
* `command 8`
* `call down 8`

### Expected

Serving a command on a bottom or top floor will also serve the up/down call on that floor if it isn't assigned to another elevator.

**Comment by kstrafe** [comment]
What about floor 1? Like
`command 1`
`call up 1`
?

What about all the other floors?

**Comment by dagerikhl** [comment]
Good point. But that would be a more demanding case I think. As we would have to know what direction the elevator is planning to go in _after_ serving `command 1` to be able to determine if it should serve an up or a down, not both.
But a better solution would handle that too, I agree.

**Comment by kstrafe** [comment]
Note: Be cautious with this update; ensure the elevator doesn't get stuck if the up/command is always pressed on floor 0

**Comment by kstrafe** [comment]
Fixed in v0.1.1
